# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]
lua-curl = "0.3.13"
xml2lua = "1.6"
mimetypes = "1.0.0"

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.36.0"
"rocks-git.nvim" = "2.0.1"
"rocks-dev.nvim" = "1.2.4"
"rocks-config.nvim" = "2.1.4"
"rocks-edit.nvim" = "scm"
"rocks-treesitter.nvim" = "scm"
# harpoon uses plenary.nvim
"plenary.nvim" = "scm"
github-nvim-theme = "1.0.2"
nvim-lspconfig = "0.1.8"
"mason.nvim" = "1.10.0"
"indent-blankline.nvim" = "3.7.1"
"conform.nvim" = "6.1.0"
"fidget.nvim" = "1.4.1"
nvim-ufo = "1.4.0"
luasnip = "2.3.0"
neogit = "scm"
"kanagawa.nvim" = "scm"
"mini.ai" = "scm"
nvim-surround = "2.1.5"
nvim-treesitter-legacy-api = "0.9.2"
fzf-lua = "0.0.1378"

tree-sitter-css = "scm"
tree-sitter-ecma = "scm"
tree-sitter-go = "scm"
tree-sitter-html = "scm"
tree-sitter-http = "scm"
tree-sitter-javascript = "scm"
tree-sitter-json = "scm"
tree-sitter-jsx = "scm"
tree-sitter-lua = "scm"
tree-sitter-make = "scm"
tree-sitter-query = "scm"
tree-sitter-rust = "scm"
tree-sitter-templ = "scm"
tree-sitter-toml = "scm"
tree-sitter-tsx = "scm"
tree-sitter-typescript = "scm"
tree-sitter-yaml = "scm"

"oil.nvim" = "2.11.0"
# nvim-cmp = { git = "hrsh7th/nvim-cmp" }
# cmp-nvim-lsp = { git = "hrsh7th/cmp-nvim-lsp" }
# for some plugins that needs legacy api (e.g. nvim-surround)
nvim-treesitter-textobjects = { dir = "~/repo/nvim-treesitter-textobjects" }
nvim-lint = "scm"
tree-sitter-gomod = "scm"
tree-sitter-dockerfile = "scm"
tree-sitter-regex = "scm"
tree-sitter-gitignore = "scm"
tree-sitter-swift = "scm"
tree-sitter-kotlin = "scm"
tree-sitter-groovy = "scm"
tree-sitter-ini = "scm"
tree-sitter-vimdoc = "scm"
tree-sitter-tmux = "scm"
"lazydev.nvim" = "1.7.1"
tree-sitter-astro = "scm"
tree-sitter-jsonc = "scm"
tree-sitter-html_tags = "scm"
tree-sitter-editorconfig = "scm"
treesj = "scm"

[plugins."gitsigns.nvim"]
git = "lewis6991/gitsigns.nvim"
rev = "v0.9.0"

[plugins."crates.nvim" ]
git = "Saecki/crates.nvim"
rev = "v0.5.1"

[plugins.harpoon]
git = "ThePrimeagen/harpoon"
rev = "0378a6c428a0bed6a2781d459d7943843f374bce"
branch = "harpoon2"

[plugins."leap.nvim"]
git = "ggandor/leap.nvim"
rev = "c099aecaf858574909bd38cbadb8543c4dd16611"

[plugins."rest.nvim"]
git = "aktersnurra/rest.nvim"
rev = "7d6de91881a1b702fca2fe1e7f5ae88670a42b2a"
branch = "fix/getregtype"

[plugins."markdown.nvim"]
# dir = "~/repo/markdown.nvim"
git = "meanderingprogrammer/markdown.nvim"
rev = "v4.1.0^{}"

[config]
auto_setup = false

[treesitter]
auto_highlight = "all"
