# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]
xml2lua = "1.6"
mimetypes = "1.0.0"
nvim-nio = "1.10.0"

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.40.0"
"rocks-git.nvim" = "2.0.1"
"rocks-dev.nvim" = "1.5.0"
"rocks-config.nvim" = "2.2.0"
"rocks-edit.nvim" = "scm"
"rocks-treesitter.nvim" = "1.1.1"
# harpoon uses plenary.nvim
"plenary.nvim" = "scm"
nvim-lspconfig = "0.1.8"
"mason.nvim" = "1.10.0"
"indent-blankline.nvim" = "3.7.2"
"conform.nvim" = "7.1.0"
"fidget.nvim" = "1.4.1"
luasnip = "2.3.0"
neogit = "scm"
"kanagawa.nvim" = "scm"
"mini.ai" = "scm"
nvim-surround = "2.1.5"
nvim-treesitter-legacy-api = "0.9.2"
fzf-lua = "0.0.1450"
"quicker.nvim" = "1.1.1"
nvim-ufo = "1.4.0"
"telescope.nvim" = "scm"
"octo.nvim" = "scm"
"oil.nvim" = "2.12.1"
nvim-lint = "scm"
treesj = "scm"
"lazydev.nvim" = "1.8.0"

tree-sitter-css = "0.0.3"
tree-sitter-ecma = "0.0.2"
tree-sitter-go = "0.0.3"
tree-sitter-html = "0.0.3"
tree-sitter-javascript = "0.0.3"
tree-sitter-json = "0.0.3"
tree-sitter-jsx = "0.0.2"
tree-sitter-lua = "0.0.2"
tree-sitter-make = "0.0.2"
tree-sitter-query = "0.0.2"
tree-sitter-rust = "0.0.3"
tree-sitter-templ = "0.0.3"
tree-sitter-toml = "0.0.2"
tree-sitter-tsx = "0.0.3"
tree-sitter-typescript = "0.0.3"
tree-sitter-yaml = "0.0.2"

# nvim-cmp = { git = "hrsh7th/nvim-cmp" }
# cmp-nvim-lsp = { git = "hrsh7th/cmp-nvim-lsp" }
# for some plugins that needs legacy api (e.g. nvim-surround)
# nvim-treesitter-textobjects = { dir = "~/repo/nvim-treesitter-textobjects" }
tree-sitter-gomod = "0.0.3"
tree-sitter-dockerfile = "0.0.2"
tree-sitter-regex = "0.0.2"
tree-sitter-gitignore = "0.0.2"
tree-sitter-swift = "0.0.3"
tree-sitter-kotlin = "0.0.4"
tree-sitter-groovy = "0.0.3"
tree-sitter-ini = "0.0.2"
tree-sitter-vimdoc = "0.0.2"
tree-sitter-tmux = "0.0.3"
tree-sitter-astro = "0.0.2"
tree-sitter-jsonc = "0.0.2"
tree-sitter-html_tags = "0.0.2"
tree-sitter-editorconfig = "0.0.4"
tree-sitter-gitattributes = "0.0.2"
tree-sitter-graphql = "0.0.2"
tree-sitter-xml = "0.0.2"
tree-sitter-nix = "0.0.5"
tree-sitter-vue = "0.0.2"
tree-sitter-hurl = "0.0.3"
"diffview.nvim" = "scm"

[plugins."gitsigns.nvim"]
git = "lewis6991/gitsigns.nvim"
rev = "v0.9.0"

[plugins."crates.nvim" ]
git = "Saecki/crates.nvim"
rev = "v0.5.2"

[plugins.harpoon]
git = "ThePrimeagen/harpoon"
rev = "0378a6c428a0bed6a2781d459d7943843f374bce"
branch = "harpoon2"

[plugins."leap.nvim"]
git = "ggandor/leap.nvim"
rev = "c099aecaf858574909bd38cbadb8543c4dd16611"

# temporary disable. this breaks all my floating windows (conceallevel and concealcursors)
# [plugins."markdown.nvim"]
# # dir = "~/repo/markdown.nvim"
# git = "meanderingprogrammer/markdown.nvim"
# rev = "v5.0.0^{}"

[plugins."kulala.nvim"]
git = "mistweaverco/kulala.nvim"
rev = "v3.5.0"

[plugins.github-nvim-theme]
git = "projekt0n/github-nvim-theme"
rev = "v1.1.2^{}"

[plugins."rest.nvim"]
dir = "~/repo/rest.nvim"

[config]
auto_setup = false

[treesitter]
auto_highlight = "all"
auto_install = false # "prompt" | true | false
