# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]
xml2lua = "1.6"
mimetypes = "1.0.0"
nvim-nio = "1.10.0"

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.40.2"
"rocks-git.nvim" = "2.3.1"
"rocks-dev.nvim" = "1.7.0"
"rocks-config.nvim" = "3.0.0"
"rocks-lazy.nvim" = "1.1.0"
"rocks-edit.nvim" = "scm"
"rocks-treesitter.nvim" = "1.1.3"

# harpoon uses plenary.nvim
"plenary.nvim" = "scm"
nvim-lspconfig = "1.0.0"
"indent-blankline.nvim" = "3.8.0"
"conform.nvim" = "8.1.0"
"fidget.nvim" = "1.4.1"
luasnip = { version = "2.3.0", event = "InsertEnter" }
neogit = { version = "scm", cmd = "Neogit" }
"kanagawa.nvim" = "scm"
"mini.ai" = "scm"
nvim-surround = "2.1.5"
# nvim-treesitter-legacy-api = "0.9.2"
fzf-lua = { version = "0.0.1472" }
"quicker.nvim" = "1.1.1"
# nvim-ufo = "1.4.0"
"telescope.nvim" = "scm"
"octo.nvim" = { version = "scm", cmd = "Octo", event = "BufReadCmd octo://*" }
"oil.nvim" = "2.12.2"
nvim-lint = "scm"
treesj = "scm"
"lazydev.nvim" = "1.8.0"

tree-sitter-astro = "0.0.27"
tree-sitter-css = "0.0.27"
tree-sitter-dockerfile = "0.0.27"
tree-sitter-ecma = "0.0.10"
tree-sitter-editorconfig = "0.0.28"
tree-sitter-gitattributes = "0.0.27"
tree-sitter-gitcommit = "0.0.27"
tree-sitter-gitignore = "0.0.27"
tree-sitter-go = "0.0.28"
tree-sitter-gomod = "0.0.28"
tree-sitter-graphql = "0.0.27"
tree-sitter-groovy = "0.0.27"
tree-sitter-html = "0.0.27"
tree-sitter-html_tags = "0.0.10"
tree-sitter-hurl = "0.0.28"
tree-sitter-ini = "0.0.27"
tree-sitter-javascript = "0.0.27"
tree-sitter-json = "0.0.27"
tree-sitter-jsonc = "0.0.27"
tree-sitter-jsx = "0.0.10"
tree-sitter-kotlin = "0.0.27"
tree-sitter-lua = "0.0.28"
tree-sitter-make = "0.0.27"
tree-sitter-nix = "0.0.35"
tree-sitter-query = "0.0.27"
tree-sitter-regex = "0.0.27"
tree-sitter-rust = "0.0.27"
tree-sitter-swift = "0.0.30"
tree-sitter-templ = "0.0.29"
tree-sitter-tmux = "0.0.27"
tree-sitter-toml = "0.0.27"
tree-sitter-tsx = "0.0.27"
tree-sitter-typescript = "0.0.27"
tree-sitter-vimdoc = "0.0.27"
tree-sitter-vue = "0.0.27"
tree-sitter-xml = "0.0.27"
tree-sitter-yaml = "0.0.27"

"diffview.nvim" = "scm"
"sweetie.nvim" = "3.2.0"
"crates.nvim" = { version = "0.5.2", event = "BufRead" }
"leap.nvim" = "scm"

[plugins."rest.nvim"]
dir = "~/repo/rest.nvim"

[plugins."sense.nvim"]
dir = "~/projects/sense.nvim/"

[plugins.github-nvim-theme]
git = "projekt0n/github-nvim-theme"
rev = "v1.1.2^{}"

[config]
auto_setup = false

[treesitter]
auto_highlight = "all"
auto_install = false # "prompt" | true | false
