# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]
xml2lua = "1.6"
mimetypes = "1.0.0"
nvim-nio = "1.10.0"

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.43.0"
"rocks-git.nvim" = "2.5.2"
"rocks-dev.nvim" = "1.7.0"
"rocks-config.nvim" = "3.1.0"
"rocks-lazy.nvim" = "1.1.1"
"rocks-edit.nvim" = "scm"
"rocks-treesitter.nvim" = "1.3.0"

nvim-lspconfig = "1.2.0"
"indent-blankline.nvim" = "3.8.6"
"conform.nvim" = "8.3.0"
"fidget.nvim" = "1.4.1"
luasnip = { version = "2.3.0", event = "InsertEnter" }
neogit = { version = "scm", cmd = "Neogit" }
"kanagawa.nvim" = "scm"
"mini.ai" = "scm"
nvim-surround = "2.1.5"
fzf-lua = { version = "0.0.1594" }
"quicker.nvim" = "1.3.0"
"telescope.nvim" = "scm"
"octo.nvim" = { version = "scm", cmd = "Octo", event = "BufReadCmd octo://*" }
"oil.nvim" = "2.14.0"
nvim-lint = "scm"
treesj = "scm"
"lazydev.nvim" = "1.9.0"

tree-sitter-astro = "0.0.33"
tree-sitter-css = "0.0.31"
tree-sitter-dockerfile = "0.0.29"
tree-sitter-ecma = "0.0.10"
tree-sitter-editorconfig = "0.0.45"
tree-sitter-gitattributes = "0.0.30"
tree-sitter-gitcommit = "0.0.33"
tree-sitter-gitignore = "0.0.29"
tree-sitter-go = "0.0.36"
tree-sitter-gomod = "0.0.31"
tree-sitter-graphql = "0.0.29"
tree-sitter-groovy = "0.0.30"
tree-sitter-html = "0.0.33"
tree-sitter-html_tags = "0.0.10"
tree-sitter-hurl = "0.0.30"
tree-sitter-ini = "0.0.29"
tree-sitter-javascript = "0.0.33"
tree-sitter-json = "0.0.33"
tree-sitter-jsonc = "0.0.29"
tree-sitter-jsx = "0.0.10"
tree-sitter-kotlin = "0.0.31"
tree-sitter-lua = "0.0.32"
tree-sitter-make = "0.0.29"
tree-sitter-nix = "0.0.51"
tree-sitter-query = "0.0.30"
tree-sitter-regex = "0.0.38"
tree-sitter-rust = "0.0.38"
tree-sitter-swift = "0.0.42"
tree-sitter-templ = "0.0.42"
tree-sitter-tmux = "0.0.29"
tree-sitter-toml = "0.0.31"
tree-sitter-tsx = "0.0.32"
tree-sitter-typescript = "0.0.32"
tree-sitter-vimdoc = "0.0.31"
tree-sitter-vue = "0.0.29"
tree-sitter-xml = "0.0.34"
tree-sitter-yaml = "0.0.30"

"diffview.nvim" = "scm"
"sweetie.nvim" = "3.2.0"
"crates.nvim" = { version = "0.5.2", event = "BufRead" }
"leap.nvim" = "scm"
"gitsigns.nvim" = "0.9.0"
tree-sitter-dart = "0.0.34"
tree-sitter-sql = "0.0.38"
nvim-treesitter-legacy-api = "0.9.2"
neorg = "9.1.1"

# [plugins."sense.nvim"]
# dir = "~/projects/sense.nvim/"
[plugins."rest.nvim"]
dir = "~/repo/rest.nvim/"

[plugins.github-nvim-theme]
git = "projekt0n/github-nvim-theme"
rev = "v1.1.2^{}"

[config]
auto_setup = false

[treesitter]
auto_highlight = "all"
auto_install = false # "prompt" | true | false
