vim.keymap.set("n", "<leader>1", "<cmd>Grapple select index=1<cr>")
vim.keymap.set("n", "<leader>2", "<cmd>Grapple select index=2<cr>")
vim.keymap.set("n", "<leader>3", "<cmd>Grapple select index=3<cr>")
vim.keymap.set("n", "<leader>4", "<cmd>Grapple select index=4<cr>")
vim.keymap.set("n", "<leader>5", "<cmd>Grapple select index=5<cr>")
vim.keymap.set("n", "<leader>6", "<cmd>Grapple select index=6<cr>")
vim.keymap.set("n", "<leader>7", "<cmd>Grapple select index=7<cr>")
vim.keymap.set("n", "<leader>8", "<cmd>Grapple select index=8<cr>")
vim.keymap.set("n", "<leader>9", "<cmd>Grapple select index=9<cr>")
vim.keymap.set("n", "<leader>0", "<cmd>Grapple toggle<cr>")
vim.keymap.set("n", "<leader><leader>", "<cmd>Grapple toggle_tags<cr>")
